# For more info on HTTP files go to https://aka.ms/vs/httpfile
@apiUrl = https://localhost:7010/api/v1

############################################################
# AUTHENTIFICATION

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
"email": "test@vuv.hr",
"password": "P@ssw0rd"
}
###

GET {{apiUrl}}/auth/test
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjVkMGQwZC01YmU1LTRhN2UtYjU4YS1kZmY4MDM3NWVkNTQiLCJlbWFpbCI6InRlc3RAdnV2LmhyIiwiZW1haWxfdmVyaWZpZWQiOiJGYWxzZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMTAiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDEwIiwiZXhwIjoxNzI2NDY3NTM4LCJpYXQiOjE3MjY0NjU3MzgsIm5iZiI6MTcyNjQ2NTczOH0.Y0ciViRhCJgg47pW9tVjJ2RZBI7RpA5esM1ZRrzAs7oxYLIhAJtA-Oueg_kkloNjqFhPUpyi9HAGNRGeKYIAcA
####

POST {{apiUrl}}/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjVkMGQwZC01YmU1LTRhN2UtYjU4YS1kZmY4MDM3NWVkNTQiLCJlbWFpbCI6InRlc3RAdnV2LmhyIiwiZW1haWxfdmVyaWZpZWQiOiJGYWxzZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMTAiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDEwIiwiZXhwIjoxNzI2NDY3NTM4LCJpYXQiOjE3MjY0NjU3MzgsIm5iZiI6MTcyNjQ2NTczOH0.Y0ciViRhCJgg47pW9tVjJ2RZBI7RpA5esM1ZRrzAs7oxYLIhAJtA-Oueg_kkloNjqFhPUpyi9HAGNRGeKYIAcA

############################################################
# TASKS
GET {{apiUrl}}/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjVkMGQwZC01YmU1LTRhN2UtYjU4YS1kZmY4MDM3NWVkNTQiLCJlbWFpbCI6InRlc3RAdnV2LmhyIiwiZW1haWxfdmVyaWZpZWQiOiJGYWxzZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMTAiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDEwIiwiZXhwIjoxNzI2NDc3NjU4LCJpYXQiOjE3MjY0NzU4NTgsIm5iZiI6MTcyNjQ3NTg1OH0.lMaMOmOAda1wkRVpMcuFhjB9auwOE2KxFZQOw96ThcWqV7ktMGglaFTRr3vjmDqkDM4V2P7QNF_SlSS95Pz87A
###
