@JustDoIt.API_HostAddress = https://localhost:7010/api/v1
@auth_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMWYwOGI1ZC0xNDVjLTRiZTItOGQzOC1hNmI0NmRkMDA0NmEiLCJlbWFpbCI6ImRhcmlvLnJ1cGNpY0B2dXYuaHIiLCJlbWFpbF92ZXJpZmllZCI6IkZhbHNlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTE3MztodHRwczovL2xvY2FsaG9zdDo3MDEwIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAxMCIsImV4cCI6MTcyNjY4NjYxMywiaWF0IjoxNzI2Njg0ODEzLCJuYmYiOjE3MjY2ODQ4MTN9.zZ6cyAU2EqbNsmAlcDX4NYVuxjgtUOSw6IRomgRv2c3rSinaUR7w_NHBoTJDIPTprM14FBml-yGGJMM5_cwmeQ
############################################################
# AUTHENTIFICATION

POST {{JustDoIt.API_HostAddress}}/auth/register
Content-Type: application/json

{
"email": "test@vuv.hr",
"password": "Lozinka123!"
}
###
POST {{JustDoIt.API_HostAddress}}/auth/login
Content-Type: application/json

{
"email": "dario.rupcic@vuv.hr",
"password": "Lozinka123!",
"rememberme":false
}
###

GET {{JustDoIt.API_HostAddress}}/auth/test
Authorization: Bearer {{auth_token}}
####

POST {{JustDoIt.API_HostAddress}}/auth/logout
Authorization: Bearer {{auth_token}}

############################################################
# TASKS

GET {{JustDoIt.API_HostAddress}}/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}
###

GET {{JustDoIt.API_HostAddress}}/projects/user
Content-Type: application/json
Authorization: Bearer {{auth_token}}
###
GET {{JustDoIt.API_HostAddress}}/auth/userdata
Content-Type: application/json
Authorization: Bearer {{auth_token}}

