@JustDoIt.API_HostAddress = https://localhost:7010/api/v1
@auth_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjVkMGQwZC01YmU1LTRhN2UtYjU4YS1kZmY4MDM3NWVkNTQiLCJlbWFpbCI6InRlc3RAdnV2LmhyIiwiZW1haWxfdmVyaWZpZWQiOiJGYWxzZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUxNzM7aHR0cHM6Ly9sb2NhbGhvc3Q6NzAxMCIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMTAiLCJleHAiOjE3MjY2NjcxNzYsImlhdCI6MTcyNjY2NTM3NiwibmJmIjoxNzI2NjY1Mzc2fQ.j55WO8wIyEYHJegrgdUv3Di1cUka7u5CfDsC8GazFBdb3GeTg-sJTI_WNFlZ0tQxlgeVAW5-WJkhiXi9Iqi9ew
############################################################
# AUTHENTIFICATION

POST {{JustDoIt.API_HostAddress}}/auth/register
Content-Type: application/json

{
"email": "test@vuv.hr",
"password": "Lozinka123!"
}
###
POST {{JustDoIt.API_HostAddress}}/auth/login
Content-Type: application/json

{
"email": "test@vuv.hr",
"password": "Lozinka123!",
"rememberme":false
}
###

GET {{JustDoIt.API_HostAddress}}/auth/test
Authorization: Bearer {{auth_token}}
####

POST {{JustDoIt.API_HostAddress}}/auth/logout
Authorization: Bearer {{auth_token}}

############################################################
# TASKS

GET {{JustDoIt.API_HostAddress}}/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}
###

GET {{JustDoIt.API_HostAddress}}/projects/user
Content-Type: application/json
Authorization: Bearer {{auth_token}}
###
GET {{JustDoIt.API_HostAddress}}/auth/userdata
Content-Type: application/json
Authorization: Bearer {{auth_token}}

